plugins {
    id 'com.android.application'
}

android {
    namespace 'icf.idcapture'
    compileSdk 34

    defaultConfig {
        applicationId 'icf.idcapture'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.activity:activity:1.8.2'
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
